fail_fast: false
repos:
  - repo: https://github.com/vysh2310/DebugMethod.git 
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  - repo: local
    hooks:
    -   id: build-and-analyse-with-polyspace
        name: build-and-analyse-with-polyspace
        entry: sh -x build_script.sh
        language: system
        always_run: true
        pass_filenames: false
    -   id: perform-sqo-verification
        name: perform-sqo-verification
        entry: python sqo_manager.py
        language: python
        description: Evaluates if changed files meet expected software quality objective
        always_run: true
        pass_filenames: false
